@baseUrl = http://localhost:3333
@authToken = {{authentication.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-type: application/json

{
  "name": "Marcos Souza",
  "email": "marcos1@example.com",
  "password": "1234556"
}

###

# @name authentication
POST {{baseUrl}}/sessions
Content-type: application/json

{
  "email": "marcos1@example.com",
  "password": "1234556"
}

### 

# @name create_question
POST {{baseUrl}}/questions
Content-type: application/json
Authorization: Bearer {{authToken}} 